from glob import glob

import torch

# Custom imports
import config
from predictions import predict
from utilities import make_project_dirs

# Todo
# Organize project code into a flat structure inside of src
# Figure out good way to organise data needed and generated by this project
def run_generation():
    predict()

def main():
    make_project_dirs()
    # run_training()
    run_generation()


if __name__ == "__main__":
    print("IS CUDA AVAILABLE?: ", torch.cuda.is_available())
    main()